// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqgeI4qKYiSKlH-ff5mDXCSozIXLtdfcA',
    appId: '1:410823846093:web:bb114235a4434d90ee2184',
    messagingSenderId: '410823846093',
    projectId: 'yapilacaklarlist',
    authDomain: 'yapilacaklarlist.firebaseapp.com',
    storageBucket: 'yapilacaklarlist.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHwveyJvRDffTU5zm_kFHOGoIfP_NRNSo',
    appId: '1:410823846093:android:ad1ee7155eb235c4ee2184',
    messagingSenderId: '410823846093',
    projectId: 'yapilacaklarlist',
    storageBucket: 'yapilacaklarlist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJLo5FvUZrBxqAKKJFuA9l31vr6irZ-34',
    appId: '1:410823846093:ios:329998efe5ff1e0dee2184',
    messagingSenderId: '410823846093',
    projectId: 'yapilacaklarlist',
    storageBucket: 'yapilacaklarlist.appspot.com',
    iosBundleId: 'com.example.yapilacaklarlistesi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJLo5FvUZrBxqAKKJFuA9l31vr6irZ-34',
    appId: '1:410823846093:ios:5c3bfce20e727094ee2184',
    messagingSenderId: '410823846093',
    projectId: 'yapilacaklarlist',
    storageBucket: 'yapilacaklarlist.appspot.com',
    iosBundleId: 'com.example.yapilacaklarlistesi.RunnerTests',
  );
}
